### ISSUE TITLE
Unable to transfer resource files.

### ISSUE THREAD

**Issue by hansnolte** [trumpton/PanoManager#28]
When I export to Marzipano or Pannellum, I get the following error message. 

Error Exporting Tour: 
Unable to transfer resource files.  Check they are available in the lib folder.

Then I created these folder by hand und copy the pannellum Files in... 
lib/PanoManager/pannellum
Unfortunately again the same error message.

 
I hope somebody can give me a hint.

Many greetings
Hans

Win 7 Pro 64 Bit
Pano Manager: Windows 64-bit Application (Online Install): v1.0.0 (20/06/2018) 
Offline Installer ist not avaible.

**Comment by hansnolte** [comment]
It works!

I download the Source Code from here.
https://github.com/trumpton/PanoManager/releases/tag/v1.0.0
And then I copy the lib-Folder from the Source Code-Zip in my PanoManager-Folder.

Many thanks for this great program.
Hans

**Comment by trumpton** [comment]
Hope this is now fixed in v1.0.1, which has the marzipano and pannellum install files included in the release package
