### ISSUE TITLE
Question: where should I put lib?

### ISSUE THREAD

**Issue by Riclim** [trumpton/PanoManager#29]
Can someone tell me the full folder structure where I should put the lib files extracted from the sources zip to be able to export a tour? I tried
- Program Files\PanoManager\lib\marzipano
- Program Files\PanoManager\redist\lib\marzipano
without success.

It's expected that the about dialog box shows v0.2 even if the Maintenance Tool says it's updated to the last version?

Thanks

**Comment by trumpton** [comment]
Updated install script to place files in lib/PanoManager/marzipano
Try v1.0.1
