### ISSUE TITLE
linux version?

### ISSUE THREAD

**Issue by nafergo** [trumpton/PanoManager#36]
is it possible to run this under linux?
I'm trying to use wine but no luck. Crashes even before installation.

**Comment by trumpton** [comment]
Yes, it builds OK on linux.
I'm not intending to make any Linux binaries available though, because the easiest way to produce a really portable binary is to statically link, and that is verboten with the QT library.
You can git clone and build a version yourself though!
S.

**Comment by nafergo** [comment]
I'll try to build then. Looking for a marzipano editor, so this could be very useful :)
